const data = [
  {
    id: 1,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN3 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "BELUM",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },
  {
    id: 2,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },

  {
    id: 3,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SDN5 Tanjungpinang Timur",
    tujuan_sekolah: "SDN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "BELUM",
  },
  {
    id: 4,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Batam",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "SUDAH",
  },
  {
    id: 5,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },
  {
    id: 6,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SDN5 Tanjungpinang Timur",
    tujuan_sekolah: "SDN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "BELUM",
  },
  {
    id: 7,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Batam",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "SUDAH",
  },
  {
    id: 8,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN3 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "BELUM",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },
  {
    id: 9,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },

  {
    id: 10,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SDN5 Tanjungpinang Timur",
    tujuan_sekolah: "SDN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "BELUM",
  },
  {
    id: 11,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Batam",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "SUDAH",
  },
  {
    id: 12,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },
  {
    id: 13,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SDN5 Tanjungpinang Timur",
    tujuan_sekolah: "SDN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "BELUM",
  },
  {
    id: 14,
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Batam",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "SUDAH",
  },
];

module.exports = data;
