const data = [
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN3 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "BELUM",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },

  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SDN5 Tanjungpinang Timur",
    tujuan_sekolah: "SDN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "BELUM",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Batam",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "SUDAH",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SDN5 Tanjungpinang Timur",
    tujuan_sekolah: "SDN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "BELUM",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Batam",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "SUDAH",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN3 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "BELUM",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },

  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SDN5 Tanjungpinang Timur",
    tujuan_sekolah: "SDN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "BELUM",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Batam",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "SUDAH",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "BELUM",
    status_kirim: "BELUM",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SDN5 Tanjungpinang Timur",
    tujuan_sekolah: "SDN2 Tanjungpinang Bukit Bestari",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "BELUM",
  },
  {
    tgl_naskah: "24 Jan 2022",
    hal: "Lap Pindah Sekolah",
    asal_sekolah: "SMPN5 Tanjungpinang Timur",
    tujuan_sekolah: "SMPN4 Batam",
    yang_menandatangani: "Belum Ditentukan",
    status_verifikasi: "SUDAH",
    status_ttd: "SUDAH",
    status_kirim: "SUDAH",
  },
];

module.exports = data;
